
package stockquoteservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockQuoteWSPortType", targetNamespace = "http://StockQuoteService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockQuoteWSPortType {


    /**
     * 
     * @param symbol
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "urn:getQuote")
    @WebResult(targetNamespace = "http://StockQuoteService")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://StockQuoteService", className = "stockquoteservice.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://StockQuoteService", className = "stockquoteservice.GetQuoteResponse")
    public List<String> getQuote(
        @WebParam(name = "symbol", targetNamespace = "http://StockQuoteService")
        String symbol);

    /**
     * 
     * @return
     *     returns stockquoteservice.GetFieldNamesResponse
     */
    @WebMethod(action = "urn:getFieldNames")
    @WebResult(name = "getFieldNamesResponse", targetNamespace = "http://StockQuoteService", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetFieldNamesResponse getFieldNames();

}
