
package stockquoteservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockQuoteWS", targetNamespace = "http://StockQuoteService", wsdlLocation = "http://viper.infotech.monash.edu.au:8180/ASXStockQuote/services/StockQuoteWS?wsdl")
public class StockQuoteWS
    extends Service
{

    private final static URL STOCKQUOTEWS_WSDL_LOCATION;
    private final static WebServiceException STOCKQUOTEWS_EXCEPTION;
    private final static QName STOCKQUOTEWS_QNAME = new QName("http://StockQuoteService", "StockQuoteWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://viper.infotech.monash.edu.au:8180/ASXStockQuote/services/StockQuoteWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKQUOTEWS_WSDL_LOCATION = url;
        STOCKQUOTEWS_EXCEPTION = e;
    }

    public StockQuoteWS() {
        super(__getWsdlLocation(), STOCKQUOTEWS_QNAME);
    }

    public StockQuoteWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKQUOTEWS_QNAME, features);
    }

    public StockQuoteWS(URL wsdlLocation) {
        super(wsdlLocation, STOCKQUOTEWS_QNAME);
    }

    public StockQuoteWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKQUOTEWS_QNAME, features);
    }

    public StockQuoteWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockQuoteWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteWSPortType
     */
    @WebEndpoint(name = "StockQuoteWSSOAP11port_http")
    public StockQuoteWSPortType getStockQuoteWSSOAP11PortHttp() {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteWSSOAP11port_http"), StockQuoteWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteWSPortType
     */
    @WebEndpoint(name = "StockQuoteWSSOAP11port_http")
    public StockQuoteWSPortType getStockQuoteWSSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteWSSOAP11port_http"), StockQuoteWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKQUOTEWS_EXCEPTION!= null) {
            throw STOCKQUOTEWS_EXCEPTION;
        }
        return STOCKQUOTEWS_WSDL_LOCATION;
    }

}
