
package stockquotetimelapse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockQuoteTimeLapseService", targetNamespace = "http://StockQuoteService", wsdlLocation = "http://viper.infotech.monash.edu.au:8180/axis2/services/StockQuoteTimeLapseService?wsdl")
public class StockQuoteTimeLapseService
    extends Service
{

    private final static URL STOCKQUOTETIMELAPSESERVICE_WSDL_LOCATION;
    private final static WebServiceException STOCKQUOTETIMELAPSESERVICE_EXCEPTION;
    private final static QName STOCKQUOTETIMELAPSESERVICE_QNAME = new QName("http://StockQuoteService", "StockQuoteTimeLapseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://viper.infotech.monash.edu.au:8180/axis2/services/StockQuoteTimeLapseService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKQUOTETIMELAPSESERVICE_WSDL_LOCATION = url;
        STOCKQUOTETIMELAPSESERVICE_EXCEPTION = e;
    }

    public StockQuoteTimeLapseService() {
        super(__getWsdlLocation(), STOCKQUOTETIMELAPSESERVICE_QNAME);
    }

    public StockQuoteTimeLapseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKQUOTETIMELAPSESERVICE_QNAME, features);
    }

    public StockQuoteTimeLapseService(URL wsdlLocation) {
        super(wsdlLocation, STOCKQUOTETIMELAPSESERVICE_QNAME);
    }

    public StockQuoteTimeLapseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKQUOTETIMELAPSESERVICE_QNAME, features);
    }

    public StockQuoteTimeLapseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockQuoteTimeLapseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpSoap11Endpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpSoap11Endpoint"), StockQuoteTimeLapseServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpSoap11Endpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpSoap11Endpoint"), StockQuoteTimeLapseServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpSoap12Endpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpSoap12Endpoint"), StockQuoteTimeLapseServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpSoap12Endpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpSoap12Endpoint"), StockQuoteTimeLapseServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpEndpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpEndpoint() {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpEndpoint"), StockQuoteTimeLapseServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteTimeLapseServicePortType
     */
    @WebEndpoint(name = "StockQuoteTimeLapseServiceHttpEndpoint")
    public StockQuoteTimeLapseServicePortType getStockQuoteTimeLapseServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://StockQuoteService", "StockQuoteTimeLapseServiceHttpEndpoint"), StockQuoteTimeLapseServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKQUOTETIMELAPSESERVICE_EXCEPTION!= null) {
            throw STOCKQUOTETIMELAPSESERVICE_EXCEPTION;
        }
        return STOCKQUOTETIMELAPSESERVICE_WSDL_LOCATION;
    }

}
